config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'users#login', as: 'user_login'
  post 'login', to: 'users#login', as: 'login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, allow_blank: false
  validates :password, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      'user created'
    else
      'Something went wrong'
    end
  end

  def login
    @user = User.find_by(username: params[:username], password: params[:password])
    # @user = User.find_by(user_params)

    if @user
      flash[:notice] = 'Login successful'
      # redirect_to
    else
      flash[:alert] = 'Login failed'
      # redirect_to
    end
  end

  private

  def user_params
    params.permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/login.html.erb
<h1>User#login</h1>
<p>Find me in app/views/users/login.html.erb</p>
<h2>
  <%= form_with(model: @user, url: user_login_path) do |form| %>
  <%= form.label "Username " %>
  <%= form.text_field :username, placeholder: "Username" %>
  <%= form.label "Password " %>
  <%= form.password_field :password, placeholder: "Password" %>
  <%= form.submit "Login"  %>
<% end %>
</h2>